### ISSUE TITLE
Is this plugin still actively supported?

### ISSUE THREAD

**Issue by hifihedgehog** [levelten/ga-in#1]

**Comment by philrp** [comment]
There is a lot of activity on the Wordpress.org forum : [https://wordpress.org/support/plugin/ga-in/](url)

And they ticked up the version number to take advantage of the GADWP situation.

I'd say YES it is.

**Comment by tomdude48** [comment]
Yes. I've been updating it but not pushing to wordpress.org recently. I pushed the latest version to wordpress.org.
